services:
  caddy:
    image: caddy:2.10.2
    container_name: futurefintechsurvey_caddy
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./config/caddy:/etc/caddy/:ro
      - ./data/caddy:/data
      - ./static/:/static
    environment:
      LOG_FILE: "/data/access.log"
      CADDY_DOMAIN: "http://ttodevthree.uni.lux"
      CADDY_PORT: "8080"
      CADDY_ENVIRONMENT: "development"
  api:
    image: registry.gitlab.com/uniluxembourg/snt/tto/r2s/futurefintechsurvey
    container_name: futurefintechsurvey_api
    volumes:
      - ./data/db:/db
